#!/usr/bin/env python
import rospy
import numpy as np
from ar_track_alvar_msgs.msg import AlvarMarkers
posx=0
posy=0
posz=0
def callback(markers):
       global posx
       global posy
       global posz
       for m in markers.markers:
                 marker_pose = m.pose.pose
                 pos = marker_pose.position
                 ori = marker_pose.orientation
                 posx=pos.x
                 posy=pos.y
                 posz=pos.z


rospy.init_node('ar_pose_subscriber')
sub = rospy.Subscriber("/ar_pose_marker", AlvarMarkers, callback)
rate= rospy.Rate(1)
 
camx=0.0
camy=0.45
camz=0.3
caja=0.07

while not rospy.is_shutdown():
    fx=camx-posx
    fz=camz-posy+caja
    fy=-(camy-posz)

    fx=np.round(fx,3)
    fy=np.round(fy,3)
    fz=np.round(fz,3)
    if fz<0.1:
	fz=0.11

    xd=[fy,fx,fz]
    xm=[posx,posy,posz]
    xcam=[-camy,camx,camz+caja]

    if np.array_equal(xd,xcam) == False:
        print("Posicion del base vs marcador")
        print np.round(xd,3)
        print("Posicion del camara vs marcador")
        print xm
        break
    else: 
        print("Esperando lectura")
    rate.sleep()
