#!/usr/bin/env python

import rospy
from std_msgs.msg import Float64
from std_msgs.msg import Float64MultiArray
from BraccioDEV import*

if __name__ == "__main__":
    rospy.init_node("sendJointsGzNode")
    topic1 = '/robot/joint1_position_controller/command'
    topic2 = '/robot/joint2_position_controller/command'
    topic3 = '/robot/joint3_position_controller/command'
    topic4 = '/robot/joint4_position_controller/command'
    topic5 = '/robot/joint5_position_controller/command'
    topicg = '/robot/gripper/command'
    topic6 = '/robot/joint6_position_controller/command'
    pub1 = rospy.Publisher(topic1, Float64, queue_size=10, latch=True)
    pub2 = rospy.Publisher(topic2, Float64, queue_size=10, latch=True)
    pub3 = rospy.Publisher(topic3, Float64, queue_size=10, latch=True)
    pub4 = rospy.Publisher(topic4, Float64, queue_size=10, latch=True)
    pub5 = rospy.Publisher(topic5, Float64, queue_size=10, latch=True)
    pubg = rospy.Publisher(topicg, Float64, queue_size=10, latch=True)
    pub6 = rospy.Publisher(topic6, Float64MultiArray, queue_size=10, latch=True)
    
    j1 = Float64()
    j2 = Float64()
    j3 = Float64()
    j4 = Float64()
    j5 = Float64()
    jg = Float64()
    j6 = Float64MultiArray()


    m1=0
    m2=0.75
    m3=3.1415
    m4=3.14
    m5=1.57
    m6=0
    j1.data = m1
    j2.data = m2
    j3.data = m3
    j4.data = m4
    j5.data = m5
    j6.data = [m6, m6]
    jg.data = m6

    pub1.publish(j1)
    pub2.publish(j2)
    pub3.publish(j3)
    pub4.publish(j4)
    pub5.publish(j5)
    pubg.publish(jg)
    pub6.publish(j6)

# Initial configuration
    q0 = np.array([m1,m2,m3,m4,m5])
# Initial configuration
    ms1=np.round(m1*180/3.1415,1)
    ms2=np.round(m2*180/3.1415,1)
    ms3=np.round(m3*180/3.1415,1)
    ms4=np.round(m4*180/3.1415,1)
    ms5=np.round(m5*180/3.1415,1)
    ms6=np.round(m6*180/3.1415,1)
    k = np.array([ms1,ms2,ms3,ms4,ms5])
    print("Angulos accionados")
    print(np.round(k,3))

# Resulting initial position (end effector with respect to the base link)
    T = fkine_BRT(q0)
    x0 = T[0:3,3]
    print("Posicion inicial y orientacion del efector final")
    print(np.round(T,3))
    


    rate = rospy.Rate(10)
    while not rospy.is_shutdown():
        rate.sleep()
