#!/usr/bin/env python

import rospy
import time
from std_msgs.msg import Float64
from std_msgs.msg import Float64MultiArray

if __name__ == "__main__":

    rospy.init_node("sendJointsGzNode")

    topic1 = '/robot/joint1_position_controller/command'
    topic2 = '/robot/joint2_position_controller/command'
    topic3 = '/robot/joint3_position_controller/command'
    topic4 = '/robot/joint4_position_controller/command'
    topic5 = '/robot/joint5_position_controller/command'
    topicg = '/robot/gripper/command'
    topic6 = '/robot/joint6_position_controller/command'
    pub1 = rospy.Publisher(topic1, Float64, queue_size=10, latch=True)
    pub2 = rospy.Publisher(topic2, Float64, queue_size=10, latch=True)
    pub3 = rospy.Publisher(topic3, Float64, queue_size=10, latch=True)
    pub4 = rospy.Publisher(topic4, Float64, queue_size=10, latch=True)
    pub5 = rospy.Publisher(topic5, Float64, queue_size=10, latch=True)
    pubg = rospy.Publisher(topicg, Float64, queue_size=10, latch=True)
    pub6 = rospy.Publisher(topic6, Float64MultiArray, queue_size=10, latch=True)
    
    j1 = Float64()
    j2 = Float64()
    j3 = Float64()
    j4 = Float64()
    j5 = Float64()
    jg = Float64()
    j6 = Float64MultiArray()

    m1=[1.57,1.57,0   ,0   ,0   ,1.57]
    m2=[1.1 ,1.1,1.57 ,1.57,1.57,1.57]
    m3=[0.6 ,0.6 ,0.5 ,0   ,0   ,1.57]
    m4=[0   ,0   ,0.7 ,0.7 ,0.7 ,1.57]
    m5=[1.57,1.57,0   ,1.57,1.57,1.57]
    m6=[0.5 ,3.1 ,3.1 ,3.1 ,0.5 ,1.57]

    i=0
    rate = rospy.Rate(5)
    while i <len(m1):
        
        j1.data = m1[i]
        j2.data = m2[i]
        j3.data = m3[i]
        j4.data = m4[i]
        j5.data = m5[i]
        j6.data = [m6[i], m6[i]]
        jg.data = m6[i]

        MOVE=[j1,j2,j3,j4,j5,jg]
        print(MOVE)

        pub1.publish(j1)
        pub2.publish(j2)
        pub3.publish(j3)
        pub4.publish(j4)
        pub5.publish(j5)
        pubg.publish(jg)
        pub6.publish(j6)

        time.sleep(7)
        i+=1

    while not rospy.is_shutdown():
        rate.sleep()

